name: onfido_web_sdk
description: Custom Dart package for using onfido sdk on Flutter Web.
version: 2.0.1
repository: https://github.com/alistairholmes/onfidowebsdk

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  js: 0.6.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0