name: onfido_web_sdk
description: Custom Dart package for onfido sdk.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  js: ^0.6.7

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
